# Generated by Django 3.2.8 on 2021-10-16 23:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem_Product',
            fields=[
                ('name_image', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('imagem_of_product', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mark_Product',
            fields=[
                ('name_of_mark', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description_of_mark', models.TextField()),
                ('date_of_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_Product',
            fields=[
                ('type_product', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('public_target', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('descripition', models.TextField()),
                ('inventory', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagem_product', models.ManyToManyField(to='products.Imagem_Product')),
                ('mark_of_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mark_product')),
                ('type_of_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.type_of_product')),
            ],
        ),
    ]
